### ISSUE TITLE
Indexing not working

### ISSUE THREAD

**Issue by daelba** [ad-freiburg/qlever-control#73]
I have similar issue to #41. `meta-data.json` is not created.

Ubuntu 24.04.1 LTS

`pip show qlever`:
```
Name: qlever
Version: 0.5.6
Summary: Script for using the QLever SPARQL engine.
Home-page: 
Author: 
Author-email: Hannah Bast <bast@cs.uni-freiburg.de>
License: Apache-2.0
Location: /usr/local/lib/python3.12/dist-packages
Requires: argcomplete, psutil, termcolor
Required-by: 
```

`Qleverfile`:
```
[data]
NAME              = scrap
BASE_URL          = .
GET_DATA_CMD      = echo "Using local file"
DESCRIPTION       = Scrap Dataset
TEXT_DESCRIPTION  = All literals, search with FILTER CONTAINS(?var, "...")

[index]
INPUT_FILES     = data/Q31519.ttl
CAT_INPUT_FILES = cat ${INPUT_FILES}
SETTINGS_JSON   = { "ascii-prefixes-only": false, "num-triples-per-batch": 10000 }
STXXL_MEMORX    = 10G

[server]
PORT               = 7019
ACCESS_TOKEN       = ${data:NAME}_xxxx_secret_xxxx
MEMORY_FOR_QUERIES = 5G
CACHE_MAX_SIZE     = 2G
TIMEOUT            = 30s

[runtime]
SYSTEM = docker
IMAGE  = docker.io/adfreiburg/qlever:latest

[ui]
UI_CONFIG = scrap
```
Where Q31519.ttl was downloaded from https://www.wikidata.org/wiki/Special:EntityData/Q31519.ttl. It is small file with few triples, so there can't be any memory issue.

`qlever index`:
```
Command: index

echo '{ "ascii-prefixes-only": false, "num-triples-per-batch": 10000 }' > scrap.settings.json
docker run --rm -u $(id -u):$(id -g) -v /etc/localtime:/etc/localtime:ro -v $(pwd):/index -w /index --init --entrypoint bash --name qlever.index.scrap docker.io/adfreiburg/qlever:latest -c 'cat data/Q31519.ttl | IndexBuilderMain -F ttl - -i scrap -s scrap.settings.json --stxxl-memory 5G | tee scrap.index-log.txt'

2024-10-07 11:19:16.178 - INFO: QLever IndexBuilder, compiled on Fri Oct  4 20:23:39 UTC 2024 using git hash 77ea2c
2024-10-07 11:19:16.178 - INFO: You specified the input format: TTL
2024-10-07 11:19:16.179 - INFO: Processing input triples from /dev/stdin ...
2024-10-07 11:19:16.179 - INFO: Locale was not specified in settings file, default is en_US
2024-10-07 11:19:16.181 - INFO: You specified "locale = en_US" and "ignore-punctuation = 0"
2024-10-07 11:19:16.181 - INFO: You specified "parallel-parsing = true", which enables faster parsing for TTL files with a well-behaved use of newlines
2024-10-07 11:19:16.181 - INFO: You specified "num-triples-per-batch = 10,000", choose a lower value if the index builder runs out of memory
2024-10-07 11:19:16.181 - INFO: By default, integers that cannot be represented by QLever will throw an exception
2024-10-07 11:19:16.187 - INFO: Parsing input triples and creating partial vocabularies, one per batch ...
2024-10-07 11:19:16.266 - INFO: Triples parsed: 11,217 [average speed 0.1 M/s] 
2024-10-07 11:19:16.273 - INFO: Number of triples created (including QLever-internal ones): 19,793 [may contain duplicates]
2024-10-07 11:19:16.273 - INFO: Merging partial vocabularies ...
2024-10-07 11:19:16.278 - INFO: Words merged: 5,398 [average speed 1.5 M/s]
```

`dir`:
```
data #folder
Qleverfile
scrap.index-log.txt
scrap.settings.json
scrap.tmp.partial-ids-mmap.0
scrap.tmp.partial-ids-mmap.1
scrap.tmp.partial-vocabulary.0
scrap.tmp.partial-vocabulary.1
scrap.unsorted-triples.dat
scrap.vocabulary.words.external
scrap.vocabulary.words.external.offsets
scrap.vocabulary.words.internal
scrap.vocabulary.words.internal.ids
```

Is there any problem in the Qleverfile, or is it qlever bug? Thanks.

**Comment by hannahbast** [comment]
@daelba Sorry for the late reply. That was a bug introduced by a recent commit. Fixed now by 466df71d110135925439afc26da1b27d931c823a . Please reinstall using `pip install --upgrade qlever` or `git pull` if you have have cloned https://github.com/ad-freiburg/qlever-control

**Comment by daelba** [comment]
Thanks for your reply. Now I have:
```
$ pip show qlever

Name: qlever
Version: 0.5.8
Summary: Script for using the QLever SPARQL engine.
Home-page: 
Author: 
Author-email: Hannah Bast <bast@cs.uni-freiburg.de>
License: Apache-2.0
Location: /usr/local/lib/python3.12/dist-packages
Requires: argcomplete, psutil, termcolor
Required-by: 
```
But the result is still the same.

**Comment by pkzli** [comment]
Hello, I continue on this issue while I have a similar problem. It occurs only on one specific computers. I compare here the behavior between two systems with similar OS.

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.1 LTS"
```

On both systems. 32BG ram on both systems. 8 cores on both systems. The main difference is the first (which does not work) is virtualised, while the other is bare metal.

```
$ qlever --version
qlever 0.5.12
```

On both systems. Result is the same on both systems for `qlever setup-config olympics` and `qlever get-data`. When it comes to index, I have on the first (not working)

```
$ qlever index

Command: index

echo '{ "ascii-prefixes-only": false, "num-triples-per-batch": 100000 }' > olympics.settings.json
docker run --rm -u $(id -u):$(id -g) -v /etc/localtime:/etc/localtime:ro -v $(pwd):/index -w /index --init --entrypoint bash --name qlever.index.olympics docker.io/adfreiburg/qlever:latest -c 'cat olympics.nt | IndexBuilderMain -i olympics -s olympics.settings.json -F ttl -f - --stxxl-memory 5G | tee olympics.index-log.txt'

2024-11-28 14:41:13.239 - INFO: QLever IndexBuilder, compiled on Tue Nov 26 10:41:37 UTC 2024 using git hash add092
2024-11-28 14:41:13.240 - INFO: Locale was not specified in settings file, default is en_US
2024-11-28 14:41:13.240 - INFO: You specified "locale = en_US" and "ignore-punctuation = 0"
2024-11-28 14:41:13.241 - INFO: You specified "num-triples-per-batch = 100,000", choose a lower value if the index builder runs out of memory
2024-11-28 14:41:13.241 - INFO: By default, integers that cannot be represented by QLever will throw an exception
2024-11-28 14:41:13.241 - WARN: Implicitly using the parallel parser for a single input file for reasons of backward compatibility; this is deprecated, please use the command-line option --parse-parallel or -p
2024-11-28 14:41:13.241 - INFO: Parsing triples from single input stream /dev/stdin (parallel = true) ...
2024-11-28 14:41:13.243 - INFO: Parsing input triples and creating partial vocabularies, one per batch ...
2024-11-28 14:41:16.365 - INFO: Triples parsed: 1,781,625 [average speed 0.6 M/s] 
2024-11-28 14:41:16.395 - INFO: Number of triples created (including QLever-internal ones): 2,055,677 [may contain duplicates]
2024-11-28 14:41:16.395 - INFO: Merging partial vocabularies ...
2024-11-28 14:41:17.033 - INFO: Words merged: 543,754 [average speed 0.9 M/s] 

```

while on the other the task finishes

```
$ qlever index

Command: index

echo '{ "ascii-prefixes-only": false, "num-triples-per-batch": 100000 }' > olympics.settings.json
docker run --rm -u $(id -u):$(id -g) -v /etc/localtime:/etc/localtime:ro -v $(pwd):/index -w /index --init --entrypoint bash --name qlever.index.olympics docker.io/adfreiburg/qlever:latest -c 'cat olympics.nt | IndexBuilderMain -i olympics -s olympics.settings.json -F ttl -f - --stxxl-memory 5G | tee olympics.index-log.txt'

2024-11-28 14:41:49.911 - INFO: QLever IndexBuilder, compiled on Tue Nov 26 10:41:37 UTC 2024 using git hash add092
2024-11-28 14:41:49.911 - INFO: Locale was not specified in settings file, default is en_US
2024-11-28 14:41:49.911 - INFO: You specified "locale = en_US" and "ignore-punctuation = 0"
2024-11-28 14:41:49.911 - INFO: You specified "num-triples-per-batch = 100,000", choose a lower value if the index builder runs out of memory
2024-11-28 14:41:49.911 - INFO: By default, integers that cannot be represented by QLever will throw an exception
2024-11-28 14:41:49.911 - WARN: Implicitly using the parallel parser for a single input file for reasons of backward compatibility; this is deprecated, please use the command-line option --parse-parallel or -p
2024-11-28 14:41:49.911 - INFO: Parsing triples from single input stream /dev/stdin (parallel = true) ...
2024-11-28 14:41:49.912 - INFO: Parsing input triples and creating partial vocabularies, one per batch ...
2024-11-28 14:41:52.276 - INFO: Triples parsed: 1,781,625 [average speed 0.8 M/s] 
2024-11-28 14:41:52.312 - INFO: Number of triples created (including QLever-internal ones): 2,055,677 [may contain duplicates]
2024-11-28 14:41:52.312 - INFO: Merging partial vocabularies ...
2024-11-28 14:41:52.764 - INFO: Words merged: 543,754 [average speed 1.2 M/s] 
2024-11-28 14:41:53.199 - INFO: Finished writing compressed internal vocabulary, size = 11.8 MB [uncompressed = 41.8 MB, ratio = 28%]
2024-11-28 14:41:53.199 - INFO: Number of words in external vocabulary: 543,754
2024-11-28 14:41:53.233 - INFO: Converting triples from local IDs to global IDs ...
2024-11-28 14:41:53.305 - INFO: Triples converted: 2,055,677 [average speed 28.8 M/s] 
2024-11-28 14:41:53.311 - INFO: Creating permutations SPO and SOP ...
2024-11-28 14:41:53.453 - INFO: Number of inputs to `uniqueView`: 1,781,625
2024-11-28 14:41:53.454 - INFO: Number of unique elements: 1,781,625
2024-11-28 14:41:53.454 - INFO: Triples sorted: 1,781,625 [average speed 12.6 M/s] 
2024-11-28 14:41:53.587 - INFO: Statistics for SPO: #relations = 406,700, #blocks = 39, #triples = 1,781,625
2024-11-28 14:41:53.587 - INFO: Statistics for SOP: #relations = 406,700, #blocks = 39, #triples = 1,781,625
2024-11-28 14:41:53.587 - INFO: Number of distinct patterns: 15
2024-11-28 14:41:53.587 - INFO: Number of subjects with pattern: 406,700 [all]
2024-11-28 14:41:53.587 - INFO: Total number of distinct subject-predicate pairs: 1,722,750
2024-11-28 14:41:53.587 - INFO: Average number of predicates per subject: 4.2
2024-11-28 14:41:53.587 - INFO: Average number of subjects per predicate: 107,672
2024-11-28 14:41:53.588 - INFO: Creating permutations OSP and OPS ...
2024-11-28 14:41:53.815 - INFO: Triples sorted: 1,781,625 [average speed 7.9 M/s] 
2024-11-28 14:41:53.845 - INFO: Statistics for OSP: #relations = 274,300, #blocks = 46, #triples = 1,781,625
2024-11-28 14:41:53.845 - INFO: Statistics for OPS: #relations = 274,300, #blocks = 46, #triples = 1,781,625
2024-11-28 14:41:53.846 - INFO: Adding 406,700 triples to the POS and PSO permutation for the internal `ql:has-pattern` ...
2024-11-28 14:41:53.866 - INFO: Creating permutations PSO and POS ...
2024-11-28 14:41:53.948 - INFO: Number of inputs to `uniqueView`: 680,752
2024-11-28 14:41:53.948 - INFO: Number of unique elements: 680,749
2024-11-28 14:41:53.948 - INFO: Triples sorted: 680,749 [average speed 8.4 M/s] 
2024-11-28 14:41:53.965 - INFO: Statistics for PSO: #relations = 3, #blocks = 24, #triples = 680,749
2024-11-28 14:41:53.966 - INFO: Statistics for POS: #relations = 3, #blocks = 24, #triples = 680,749
2024-11-28 14:41:53.966 - INFO: Creating permutations PSO and POS ...
2024-11-28 14:41:54.263 - INFO: Triples sorted: 1,781,625 [average speed 6.0 M/s] 
2024-11-28 14:41:54.291 - INFO: Statistics for PSO: #relations = 16, #blocks = 67, #triples = 1,781,625
2024-11-28 14:41:54.291 - INFO: Statistics for POS: #relations = 16, #blocks = 67, #triples = 1,781,625
2024-11-28 14:41:54.292 - INFO: Index build completed
```

I tried login on the container on both machines and compare the hash of executables and data and manually execute the command, everything is the same, but the command still don't finish properly.

```
$ docker run -it --rm -u $(id -u):$(id -g) -v /etc/localtime:/etc/localtime:ro -v $(pwd):/index -w /index --init --entrypoint bash --name qlever.index.olympics docker.io/adfreiburg/qlever:latest
I have no name!@4c9a3ced9b48:/index$ which IndexBuilderMain
/app//IndexBuilderMain
I have no name!@4c9a3ced9b48:/index$ sha1sum /app//IndexBuilderMain
aa4023b5f079c773ccb46493cbe7351b578f1536  /app//IndexBuilderMain
I have no name!@4c9a3ced9b48:/index$ sha1sum olympics.nt
8e4a4335a1c7984306c8264565bd43e4aa3e426a  olympics.nt
I have no name!@4c9a3ced9b48:/index$ sha1sum olympics.settings.json
88f6ca8d76f8f86a03cddf282f6bdfc58e52aff0  olympics.settings.json
I have no name!@4c9a3ced9b48:/index$ cat olympics.nt | IndexBuilderMain -i olympics -s olympics.settings.json -F ttl -f - --stxxl-memory 5G | tee olympics.index-log.txt
2024-11-28 14:44:20.840 - INFO: QLever IndexBuilder, compiled on Tue Nov 26 10:41:37 UTC 2024 using git hash add092
2024-11-28 14:44:20.841 - INFO: Locale was not specified in settings file, default is en_US
2024-11-28 14:44:20.841 - INFO: You specified "locale = en_US" and "ignore-punctuation = 0"
2024-11-28 14:44:20.841 - INFO: You specified "num-triples-per-batch = 100,000", choose a lower value if the index builder runs out of memory
2024-11-28 14:44:20.841 - INFO: By default, integers that cannot be represented by QLever will throw an exception
2024-11-28 14:44:20.841 - WARN: Implicitly using the parallel parser for a single input file for reasons of backward compatibility; this is deprecated, please use the command-line option --parse-parallel or -p
2024-11-28 14:44:20.841 - INFO: Parsing triples from single input stream /dev/stdin (parallel = true) ...
2024-11-28 14:44:20.843 - INFO: Parsing input triples and creating partial vocabularies, one per batch ...
2024-11-28 14:44:23.630 - INFO: Triples parsed: 1,781,625 [average speed 0.6 M/s] 
2024-11-28 14:44:23.707 - INFO: Number of triples created (including QLever-internal ones): 2,055,677 [may contain duplicates]
2024-11-28 14:44:23.707 - INFO: Merging partial vocabularies ...
2024-11-28 14:44:24.327 - INFO: Words merged: 543,754 [average speed 0.9 M/s]
```

and on the working system

```
$ docker run -it --rm -u $(id -u):$(id -g) -v /etc/localtime:/etc/localtime:ro -v $(pwd):/index -w /index --init --entrypoint bash --name qlever.index.olympics docker.io/adfreiburg/qlever:latest
I have no name!@81ce5ea0ff7f:/index$ sha1sum /app//IndexBuilderMain
aa4023b5f079c773ccb46493cbe7351b578f1536  /app//IndexBuilderMain
I have no name!@81ce5ea0ff7f:/index$ sha1sum olympics.nt
8e4a4335a1c7984306c8264565bd43e4aa3e426a  olympics.nt
I have no name!@81ce5ea0ff7f:/index$ sha1sum olympics.settings.json
88f6ca8d76f8f86a03cddf282f6bdfc58e52aff0  olympics.settings.json
I have no name!@81ce5ea0ff7f:/index$ cat olympics.nt | IndexBuilderMain -i olympics -s olympics.settings.json -F ttl -f - --stxxl-memory 5G | tee olympics.index-log.txt
2024-11-28 14:46:07.445 - INFO: QLever IndexBuilder, compiled on Tue Nov 26 10:41:37 UTC 2024 using git hash add092
2024-11-28 14:46:07.445 - INFO: Locale was not specified in settings file, default is en_US
2024-11-28 14:46:07.445 - INFO: You specified "locale = en_US" and "ignore-punctuation = 0"
2024-11-28 14:46:07.445 - INFO: You specified "num-triples-per-batch = 100,000", choose a lower value if the index builder runs out of memory
2024-11-28 14:46:07.445 - INFO: By default, integers that cannot be represented by QLever will throw an exception
2024-11-28 14:46:07.445 - WARN: Implicitly using the parallel parser for a single input file for reasons of backward compatibility; this is deprecated, please use the command-line option --parse-parallel or -p
2024-11-28 14:46:07.445 - INFO: Parsing triples from single input stream /dev/stdin (parallel = true) ...
2024-11-28 14:46:07.446 - INFO: Parsing input triples and creating partial vocabularies, one per batch ...
2024-11-28 14:46:10.101 - INFO: Triples parsed: 1,781,625 [average speed 0.7 M/s] 
2024-11-28 14:46:10.139 - INFO: Number of triples created (including QLever-internal ones): 2,055,677 [may contain duplicates]
2024-11-28 14:46:10.139 - INFO: Merging partial vocabularies ...
2024-11-28 14:46:10.606 - INFO: Words merged: 543,754 [average speed 1.2 M/s] 
2024-11-28 14:46:11.095 - INFO: Finished writing compressed internal vocabulary, size = 11.8 MB [uncompressed = 41.8 MB, ratio = 28%]
2024-11-28 14:46:11.111 - INFO: Number of words in external vocabulary: 543,754
2024-11-28 14:46:11.146 - INFO: Converting triples from local IDs to global IDs ...
2024-11-28 14:46:11.213 - INFO: Triples converted: 2,055,677 [average speed 30.9 M/s] 
2024-11-28 14:46:11.219 - INFO: Creating permutations SPO and SOP ...
2024-11-28 14:46:11.359 - INFO: Number of inputs to `uniqueView`: 1,781,625
2024-11-28 14:46:11.362 - INFO: Number of unique elements: 1,781,625
2024-11-28 14:46:11.362 - INFO: Triples sorted: 1,781,625 [average speed 12.6 M/s] 
2024-11-28 14:46:11.492 - INFO: Statistics for SPO: #relations = 406,700, #blocks = 39, #triples = 1,781,625
2024-11-28 14:46:11.492 - INFO: Statistics for SOP: #relations = 406,700, #blocks = 39, #triples = 1,781,625
2024-11-28 14:46:11.493 - INFO: Number of distinct patterns: 15
2024-11-28 14:46:11.493 - INFO: Number of subjects with pattern: 406,700 [all]
2024-11-28 14:46:11.493 - INFO: Total number of distinct subject-predicate pairs: 1,722,750
2024-11-28 14:46:11.493 - INFO: Average number of predicates per subject: 4.2
2024-11-28 14:46:11.493 - INFO: Average number of subjects per predicate: 107,672
2024-11-28 14:46:11.494 - INFO: Creating permutations OSP and OPS ...
2024-11-28 14:46:11.727 - INFO: Triples sorted: 1,781,625 [average speed 7.7 M/s] 
2024-11-28 14:46:11.763 - INFO: Statistics for OSP: #relations = 274,300, #blocks = 46, #triples = 1,781,625
2024-11-28 14:46:11.763 - INFO: Statistics for OPS: #relations = 274,300, #blocks = 46, #triples = 1,781,625
2024-11-28 14:46:11.764 - INFO: Adding 406,700 triples to the POS and PSO permutation for the internal `ql:has-pattern` ...
2024-11-28 14:46:11.783 - INFO: Creating permutations PSO and POS ...
2024-11-28 14:46:11.871 - INFO: Number of inputs to `uniqueView`: 680,752
2024-11-28 14:46:11.871 - INFO: Number of unique elements: 680,749
2024-11-28 14:46:11.871 - INFO: Triples sorted: 680,749 [average speed 7.9 M/s] 
2024-11-28 14:46:11.889 - INFO: Statistics for PSO: #relations = 3, #blocks = 24, #triples = 680,749
2024-11-28 14:46:11.889 - INFO: Statistics for POS: #relations = 3, #blocks = 24, #triples = 680,749
2024-11-28 14:46:11.889 - INFO: Creating permutations PSO and POS ...
2024-11-28 14:46:12.175 - INFO: Triples sorted: 1,781,625 [average speed 6.3 M/s] 
2024-11-28 14:46:12.206 - INFO: Statistics for PSO: #relations = 16, #blocks = 67, #triples = 1,781,625
2024-11-28 14:46:12.206 - INFO: Statistics for POS: #relations = 16, #blocks = 67, #triples = 1,781,625
2024-11-28 14:46:12.207 - INFO: Index build completed
```

I'm a bit at loss, because everything was working properly on both systems ~1month ago.
